---
title: "build_network"
author: "Maria Jose Herrera"
date: "9/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("igraph")
library("igraphdata")
library("tidyverse")
```


# Load data
```{r}
# Set wd
setwd("/Volumes/SAMSUNG/trpred")

# Read in file
df_data <- read_csv("data/info/20201002_submission_users.csv")

## this file based on a random sample of 50,000 unique users who commented, across all the subreddits

```

# Functions
```{r}
### found a way to separate things out a bit more in SO but not exactly sure how it does so....leaving it here for now
### "Basically, the function adds an extra vertex that is connected to all vertices belonging to the same community. The layout is calculated based on the new graph. Since each community is now connected by a common vertex, they tend to cluster together."

# # Source: http://stackoverflow.com/a/28722680/496488
layout.by.attr <- function(graph, wc, cluster.strength=1,layout=layout.auto) {
  g <- graph.edgelist(get.edgelist(graph)) # create a lightweight copy of graph w/o the attributes.
  E(g)$weight <- 1

  attr <- cbind(id=1:vcount(g), val=wc)
  g <- g + vertices(unique(attr[,2])) + igraph::edges(unlist(t(attr)), weight=cluster.strength)

  l <- layout(g, weights=E(g)$weight)[1:vcount(graph),]
  return(l)
}

```


# Create df of edges and weights

```{r}
set.seed(1)

# Generate network using first two columns (subreddit_1 and subreddit_2)
subreddits <- graph.edgelist(as.matrix(df_data[,1:2]), directed = FALSE) # Note that while above I created a new object that was the matrix and then created the graph, that's not necessary; you can have that step simply as a nested operation within the parentheses
summary(subreddits)

### TODO: ADD WEIGHT BY COLUMN 3 (common_users)

# Set weight by number of common users
E(subreddits)$weight <- df_data$common_users

# Set layout
dlayout <- layout.fruchterman.reingold(subreddits)


# Plot the graph
plot(subreddits, 
     edge.width = 0.5, 
     vertex.size = degree(subreddits)/10, 
     vertex.label = V(subreddits)$name,
     vertex.label.cex = 0.5,
     layout = dlayout)




```

# Bipartite graphs?

```{r}
setwd("/Volumes/SAMSUNG/trpred")

# Load in data
df_bipart <- read_csv("data/info/20201003_submissions_allauthors.csv")

# Check that users don't have same name as subreddits
table(unique(df_bipart$author) %in% unique(df_bipart$subreddit)) ## there are some overlaps

overlap <- intersect(unique(df_bipart$author), unique(df_bipart$subreddit)) 

# replace overlapping users by adding "u_" to their name
df_bipart$final_user <- ifelse(df_bipart$author %in% overlap, paste0("u_", df_bipart$author), df_bipart$author)

``` 

```{r}
# Create mapping
allauthors_edges <- as.matrix(data.frame(df_bipartite$final_author, df_bipartitle$subreddit))

bi_subreddits <- graph.edgelist(allauthors_edges)

V(bi_subreddits)$type <- V(bi_subreddits)$name %in% allauthors_edges[,1]

# IGRAPH 14e4d5c DN-B 235890 277830 -- : we have a bipartite graph

# bipartite.projection(bi_subreddits) ## this isn't working for some reason so check to see where subreddits are connected to eachother directly

## get bipartite working

```

